version: '3.9'

services:
  mysql_db:
    image: mysql:8.0
    container_name: my_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask_app:
    build: .  # Assumes your Dockerfile is in the same directory
    image: flask_example_repo/flask_app:latest
    container_name: my_flask_app
    depends_on:
      - mysql_db
    ports:
      - "5000:5000"
    volumes:
      # Mount current directory (host) into /app (container)
      - .:/app
    # If your Flask app needs environment variables for config, add them here
    environment:
      FLASK_ENV: development

volumes:
  db_data:
